version: "3.9"

services:
  telegram-bot:
    container_name: telegram_gpt_bot-bot
    working_dir: /telegram_gpt_bot
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "python3 main.py"